### ISSUE TITLE
倍率预测

### ISSUE THREAD

**Issue by Ljcasdasd** [Passer1072/RookieAI_yolov8#12]

**Comment by Ljcasdasd** [comment]
倍率预测理论上有高于1.0的吗

**Comment by Ljcasdasd** [comment]
将lockspeed调低到合适位置，把倍率预测调高，屏幕中心移动比（lockspeed调高，倍率预测降低顺滑）。

**Comment by Passer1072** [comment]
> 倍率预测理论上有高于1.0的吗

不能大于1，这个功能最终实现的效果与直接提高lockspeed效果一样，直观表现都是瞄准速度的增加，之后还需要修改下逻辑。目前主要将其用于分段瞄准的一阶段提高锁死跟枪效率还不错。
