### ISSUE TITLE
[Question]瞄准偏差

### ISSUE THREAD

**Issue by molanp** [Passer1072/RookieAI_yolov8#13]
在敌人静止不动时，瞄准位置（头部）总是和实际头部位置错位了一段（偏右），好像没有什么参数能够控制？

**Comment by Passer1072** [comment]
在最新V2.3.3(test)测试版中我加入了水平偏移，但是还没添加GUI界面只能通过配置文件进行更改。
参数名：aimOffset_Magnification_x
默认值：0
解释：最左为1，最右为-1，中间（默认）为0，可为小数
例：aimOffset_Magnification_x = 0

**Comment by molanp** [comment]
还有一件事，似乎控制台输出太多了
我把所有print都注释，还是有输出
```
Screen Capture FPS: 371

0: 640x640 (no detections), 7.6ms
Speed: 4.1ms preprocess, 7.6ms inference, 25.5ms postprocess per image at shape (1, 3, 640, 640)
```
这种提示关不掉啊，刷屏了，看不到想要的数据信息

**Comment by Passer1072** [comment]
> 还有一件事，似乎控制台输出太多了 我把所有print都注释，还是有输出
> 
> ```
> Screen Capture FPS: 371
> 
> 0: 640x640 (no detections), 7.6ms
> Speed: 4.1ms preprocess, 7.6ms inference, 25.5ms postprocess per image at shape (1, 3, 640, 640)
> ```
> 
> 这种提示关不掉啊，刷屏了，看不到想要的数据信息


0: 640x640 (no detections), 7.6ms
Speed: 4.1ms preprocess, 7.6ms inference, 25.5ms postprocess per image at shape (1, 3, 640, 640)
这部分是YOLO库中内建的打印，在推理部分加入参数`verbose=False`即可关闭
例如：
```
        # 检测和跟踪对象（推理部分）
        results = model.predict(frame, save=False, conf=confidence, half=True, agnostic_nms=True, iou=0.7
                                , classes=[target_selection], device="cuda:0", verbose=False)
```

**Comment by molanp** [comment]
> > 还有一件事，似乎控制台输出太多了 我把所有print都注释，还是有输出
> > 
> > ```
> > Screen Capture FPS: 371
> > 
> > 0: 640x640 (no detections), 7.6ms
> > Speed: 4.1ms preprocess, 7.6ms inference, 25.5ms postprocess per image at shape (1, 3, 640, 640)
> > ```
> > 
> > 这种提示关不掉啊，刷屏了，看不到想要的数据信息
> 
> 
> 0: 640x640 (no detections), 7.6ms
> Speed: 4.1ms preprocess, 7.6ms inference, 25.5ms postprocess per image at shape (1, 3, 640, 640)
> 这部分是YOLO库中内建的打印，在推理部分加入参数`verbose=False`即可关闭
> 例如：
> ```
>         # 检测和跟踪对象（推理部分）
>         results = model.predict(frame, save=False, conf=confidence, half=True, agnostic_nms=True, iou=0.7
>                                 , classes=[target_selection], device="cuda:0", verbose=False)
> ```

好的谢谢

**Comment by molanp** [comment]
热键要不要加个CTRL,都是鼠标上的键没法映射到键盘（

**Comment by Passer1072** [comment]
> 热键要不要加个CTRL,都是鼠标上的键没法映射到键盘（

计划中了，这个月太忙我抽空或者下个月加上

**Comment by miiiiiint** [comment]
在主程序中985行处增加
elif key =='ctrl':
    lockKey = 0x11
另外建议作者进行ui和主程序的分离

**Comment by Passer1072** [comment]
> 在主程序中985行处增加 elif key =='ctrl': lockKey = 0x11 另外建议作者进行ui和主程序的分离

好的，在考虑重构整个程序,UI改为使用PyQt库，现在这个自己看着都乱XD
