### ISSUE TITLE
解除锁fps限制

### ISSUE THREAD

**Issue by whilemoyan** [Passer1072/RookieAI_yolov8#15]
哥你dx截图锁fps怎么解除我测试一下游戏的适合感觉30
fps不太够用

**Comment by whilemoyan** [comment]
我显示是3060

**Comment by Passer1072** [comment]
> 我显卡是3060

配置文件中修改dxcam_maxFPS参数即可，但不建议超过30。

3060建议优先尝试mss截图延迟更低，用Dxcam效果并不好，截图延迟高。游戏内画质尽量降低腾出更多资源给ai

**Comment by whilemoyan** [comment]
跑太慢跟不上

**Comment by whilemoyan** [comment]
当前截图模式：mss
Exception in thread Thread-1 (main_program_loop):
Traceback (most recent call last):
  File "E:\py11\Lib\threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "E:\py11\Lib\threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "c:\Users\Administrator\Downloads\RookieAI_yolov8-main\RookieAI_YOLOv8_V2.4.0(test).py", line 1363, in main_program_loop
    frame = capture_screen(monitor, sct)  # mss截图方式
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Administrator\Downloads\RookieAI_yolov8-main\RookieAI_YOLOv8_V2.4.0(test).py", line 199, in capture_screen
    screenshot = sct.grab(monitor)
                 ^^^^^^^^^^^^^^^^^
  File "E:\py11\Lib\site-packages\mss\base.py", line 90, in grab
    screenshot = self._grab_impl(monitor)
                 ^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\py11\Lib\site-packages\mss\windows.py", line 235, in _grab_impl
    srcdc, memdc = self._handles.srcdc, self._handles.memdc
                   ^^^^^^^^^^^^^^^^^^^
AttributeError: '_thread._local' object has no attribute 'srcdc'我用mss的报错

**Comment by Passer1072** [comment]
> 当前截图模式：mss
> 
> Exception in thread Thread-1 (main_program_loop):
> 
> Traceback (most recent call last):
> 
>   File "E:\py11\Lib\threading.py", line 1045, in _bootstrap_inner
> 
>     self.run()
> 
>   File "E:\py11\Lib\threading.py", line 982, in run
> 
>     self._target(*self._args, **self._kwargs)
> 
>   File "c:\Users\Administrator\Downloads\RookieAI_yolov8-main\RookieAI_YOLOv8_V2.4.0(test).py", line 1363, in main_program_loop
> 
>     frame = capture_screen(monitor, sct)  # mss截图方式
> 
>             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "c:\Users\Administrator\Downloads\RookieAI_yolov8-main\RookieAI_YOLOv8_V2.4.0(test).py", line 199, in capture_screen
> 
>     screenshot = sct.grab(monitor)
> 
>                  ^^^^^^^^^^^^^^^^^
> 
>   File "E:\py11\Lib\site-packages\mss\base.py", line 90, in grab
> 
>     screenshot = self._grab_impl(monitor)
> 
>                  ^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "E:\py11\Lib\site-packages\mss\windows.py", line 235, in _grab_impl
> 
>     srcdc, memdc = self._handles.srcdc, self._handles.memdc
> 
>                    ^^^^^^^^^^^^^^^^^^^
> 
> AttributeError: '_thread._local' object has no attribute 'srcdc'我用mss的报错

高版本Python确实有这个问题
用Python3.9试下
安装requirements.txt内指定的库版本

**Comment by whilemoyan** [comment]
好的谢谢哥

**Comment by molanp** [comment]
dxcam原来可用吗，我截出来是一片黑

**Comment by Sakura9007** [comment]
哥，dx截图黑屏是什么原因

**Comment by molanp** [comment]
> 哥，dx截图黑屏是什么原因

可能不支持，换mms就行

**Comment by Passer1072** [comment]
> 哥，dx截图黑屏是什么原因

DX截图黑屏在研究了，可能与打包环境有关。
