### ISSUE TITLE
测试窗口可以识别到敌人但是无法锁定

### ISSUE THREAD

**Issue by T1de2077** [Passer1072/RookieAI_yolov8#19]
![image](https://github.com/Passer1072/RookieAI_yolov8/assets/97113548/4c8ebd2e-306e-4bdb-b11e-293571286fe6)
![image](https://github.com/Passer1072/RookieAI_yolov8/assets/97113548/3e992286-bee8-4532-a9b7-bcad3b3a319f)
![image](https://github.com/Passer1072/RookieAI_yolov8/assets/97113548/470f5e71-c3f4-45ba-85c2-2240f0a4e965)
![image](https://github.com/Passer1072/RookieAI_yolov8/assets/97113548/470f5e71-c3f4-45ba-85c2-2240f0a4e965)
![image](https://github.com/Passer1072/RookieAI_yolov8/assets/97113548/7e7ba719-e344-48e6-9014-e7b82c13d639)
锁定无效是咋回事？

**Comment by miiiiiint** [comment]
可能是移动鼠标的操作被程序屏蔽了，也许你可以换一个程序进行尝试

**Comment by Passer1072** [comment]
> ![图像](https://private-user-images.githubusercontent.com/97113548/342716184-4c8ebd2e-306e-4bdb-b11e-293571286fe6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzNDA2NzksIm5iZiI6MTcxOTM0MDM3OSwicGF0aCI6Ii85NzExMzU0OC8zNDI3MTYxODQtNGM4ZWJkMmUtMzA2ZS00YmRiLWIxMWUtMjkzNTcxMjg2ZmU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI1VDE4MzI1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNiYzY2YWVmMTBiMWE0NmJlNzZlM2ZiNTFiYmNlOTczNDA2Yzk3MzQ5ZDAyNWUxMDZhNTFjNGI3NmVkMGUyMDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.J0myJ7Kwx-oyrjB4oonn_dZxADYzHKqffIFmZU4BAHU) ![图像](https://private-user-images.githubusercontent.com/97113548/342716519-3e992286-bee8-4532-a9b7-bcad3b3a319f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzNDA2NzksIm5iZiI6MTcxOTM0MDM3OSwicGF0aCI6Ii85NzExMzU0OC8zNDI3MTY1MTktM2U5OTIyODYtYmVlOC00NTMyLWE5YjctYmNhZDNiM2EzMTlmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI1VDE4MzI1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJkNTlhMTg5OTQwZjIxYWE5MzMyNzlkNTgwNDNjNDJjMDcxMTE2MGVlNmZmNTQxOTNkNmRmOTNiMDk1YWRlODMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QpKpFaVMy40i68DV13FAAvNAa3oUtciN-cwVnbGaBuY) ![图像](https://private-user-images.githubusercontent.com/97113548/342716574-470f5e71-c3f4-45ba-85c2-2240f0a4e965.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzNDA2NzksIm5iZiI6MTcxOTM0MDM3OSwicGF0aCI6Ii85NzExMzU0OC8zNDI3MTY1NzQtNDcwZjVlNzEtYzNmNC00NWJhLTg1YzItMjI0MGYwYTRlOTY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI1VDE4MzI1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNlOTkyY2E0ZTI0ZjE5YjI0YzBjNmQ0NWI1Yzg4ZWFkMWZkYzgxYWQzOGM1ZTc5ZmQxZDNkMjJjYWJmN2U5NGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zTljcN7XFhOaNbETmSzRw5vxBYm_D4quvFLAV8QDhg8) ![图像](https://private-user-images.githubusercontent.com/97113548/342716574-470f5e71-c3f4-45ba-85c2-2240f0a4e965.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzNDA2NzksIm5iZiI6MTcxOTM0MDM3OSwicGF0aCI6Ii85NzExMzU0OC8zNDI3MTY1NzQtNDcwZjVlNzEtYzNmNC00NWJhLTg1YzItMjI0MGYwYTRlOTY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI1VDE4MzI1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNlOTkyY2E0ZTI0ZjE5YjI0YzBjNmQ0NWI1Yzg4ZWFkMWZkYzgxYWQzOGM1ZTc5ZmQxZDNkMjJjYWJmN2U5NGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zTljcN7XFhOaNbETmSzRw5vxBYm_D4quvFLAV8QDhg8) ![图像](https://private-user-images.githubusercontent.com/97113548/342716711-7e7ba719-e344-48e6-9014-e7b82c13d639.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzNDA2NzksIm5iZiI6MTcxOTM0MDM3OSwicGF0aCI6Ii85NzExMzU0OC8zNDI3MTY3MTEtN2U3YmE3MTktZTM0NC00OGU2LTkwMTQtZTdiODJjMTNkNjM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI1VDE4MzI1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZiYjRkZTBmMTI0ZTkyZmNiN2Y4ZmZjNGI1M2UzNjYxYmMxMzI5ODk2Y2Q0YzMzMWE1ZTMwOTBmZWE5NDdjNzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aGUw7XKha0JjgAStK3Vv2fjYOQt8wD_lNzGCVIt3gb8) 锁定有效怎么办？

找到错误，前两天鼠标移动方式改为了mouse库，APEX屏蔽了这个库所以永不了，已回滚到上个版本使用win32库可以使用

**Comment by T1de2077** [comment]
> > ![图像](https://private-user-images.githubusercontent.com/97113548/342716184-4c8ebd2e-306e-4bdb-b11e-293571286fe6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzNDA2NzksIm5iZiI6MTcxOTM0MDM3OSwicGF0aCI6Ii85NzExMzU0OC8zNDI3MTYxODQtNGM4ZWJkMmUtMzA2ZS00YmRiLWIxMWUtMjkzNTcxMjg2ZmU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI1VDE4MzI1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNiYzY2YWVmMTBiMWE0NmJlNzZlM2ZiNTFiYmNlOTczNDA2Yzk3MzQ5ZDAyNWUxMDZhNTFjNGI3NmVkMGUyMDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.J0myJ7Kwx-oyrjB4oonn_dZxADYzHKqffIFmZU4BAHU) ![图像](https://private-user-images.githubusercontent.com/97113548/342716519-3e992286-bee8-4532-a9b7-bcad3b3a319f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzNDA2NzksIm5iZiI6MTcxOTM0MDM3OSwicGF0aCI6Ii85NzExMzU0OC8zNDI3MTY1MTktM2U5OTIyODYtYmVlOC00NTMyLWE5YjctYmNhZDNiM2EzMTlmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI1VDE4MzI1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJkNTlhMTg5OTQwZjIxYWE5MzMyNzlkNTgwNDNjNDJjMDcxMTE2MGVlNmZmNTQxOTNkNmRmOTNiMDk1YWRlODMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QpKpFaVMy40i68DV13FAAvNAa3oUtciN-cwVnbGaBuY) ![图像](https://private-user-images.githubusercontent.com/97113548/342716574-470f5e71-c3f4-45ba-85c2-2240f0a4e965.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzNDA2NzksIm5iZiI6MTcxOTM0MDM3OSwicGF0aCI6Ii85NzExMzU0OC8zNDI3MTY1NzQtNDcwZjVlNzEtYzNmNC00NWJhLTg1YzItMjI0MGYwYTRlOTY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI1VDE4MzI1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNlOTkyY2E0ZTI0ZjE5YjI0YzBjNmQ0NWI1Yzg4ZWFkMWZkYzgxYWQzOGM1ZTc5ZmQxZDNkMjJjYWJmN2U5NGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zTljcN7XFhOaNbETmSzRw5vxBYm_D4quvFLAV8QDhg8) ![图像](https://private-user-images.githubusercontent.com/97113548/342716574-470f5e71-c3f4-45ba-85c2-2240f0a4e965.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzNDA2NzksIm5iZiI6MTcxOTM0MDM3OSwicGF0aCI6Ii85NzExMzU0OC8zNDI3MTY1NzQtNDcwZjVlNzEtYzNmNC00NWJhLTg1YzItMjI0MGYwYTRlOTY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI1VDE4MzI1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNlOTkyY2E0ZTI0ZjE5YjI0YzBjNmQ0NWI1Yzg4ZWFkMWZkYzgxYWQzOGM1ZTc5ZmQxZDNkMjJjYWJmN2U5NGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zTljcN7XFhOaNbETmSzRw5vxBYm_D4quvFLAV8QDhg8) ![图像](https://private-user-images.githubusercontent.com/97113548/342716711-7e7ba719-e344-48e6-9014-e7b82c13d639.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzNDA2NzksIm5iZiI6MTcxOTM0MDM3OSwicGF0aCI6Ii85NzExMzU0OC8zNDI3MTY3MTEtN2U3YmE3MTktZTM0NC00OGU2LTkwMTQtZTdiODJjMTNkNjM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI1VDE4MzI1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZiYjRkZTBmMTI0ZTkyZmNiN2Y4ZmZjNGI1M2UzNjYxYmMxMzI5ODk2Y2Q0YzMzMWE1ZTMwOTBmZWE5NDdjNzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aGUw7XKha0JjgAStK3Vv2fjYOQt8wD_lNzGCVIt3gb8) 锁定有效怎么办？
> 
> 找到错误，前两天鼠标移动方式改为了mouse库，APEX屏蔽了这个库所以永不了，已回滚到上个版本使用win32库可以使用

我使用了2.3.3 tese版可以使用了，导入我自己的pt文件不能识别是咋回事呢？

**Comment by T1de2077** [comment]
> 可能是移动鼠标的操作被程序屏蔽了，也许你可以换一个程序进行尝试

我使用了2.3.3 tese版可以使用了，导入我自己的pt文件不能识别是咋回事呢？

**Comment by miiiiiint** [comment]
1.可能你自己训练的模型参数量不够
2.你的模型里标签类型名应该和程序的一致（好像头是0，身体是1我没仔细看）
另外你的comment会被所以关注此issue的人收到，你不需要发两次

**Comment by Passer1072** [comment]
> > 可能是移动鼠标的操作被程序屏蔽了，也许你可以换一个程序进行尝试
> 
> 我使用了2.3.3 tese版可以使用了，导入我自己的pt文件不能识别是咋回事呢？

检查你训练配置文件标签名编号，根据编号适当修改程序内标号设定
训练配置文件：
![屏幕截图 2024-06-26 134724](https://github.com/Passer1072/RookieAI_yolov8/assets/145087619/128dc6e9-bc35-43a6-9bed-5b76a4201e2c)

程序内编号：
![屏幕截图 2024-06-26 134542](https://github.com/Passer1072/RookieAI_yolov8/assets/145087619/5cda9979-c1f3-4e32-8dcf-0f7515e0401b)

**Comment by T1de2077** [comment]
> > > 可能是移动鼠标的操作被程序屏蔽了，也许你可以换一个程序进行尝试
> > 
> > 
> > 我使用了2.3.3 tese版可以使用了，导入我自己的pt文件不能识别是咋回事呢？
> 
> 检查你训练配置文件标签名编号，根据编号适当修改程序内标号设定 训练配置文件： ![屏幕截图 2024-06-26 134724](https://private-user-images.githubusercontent.com/145087619/343023850-128dc6e9-bc35-43a6-9bed-5b76a4201e2c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0NDcxMTcsIm5iZiI6MTcxOTQ0NjgxNywicGF0aCI6Ii8xNDUwODc2MTkvMzQzMDIzODUwLTEyOGRjNmU5LWJjMzUtNDNhNi05YmVkLTViNzZhNDIwMWUyYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyN1QwMDA2NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MDVkMzhmYzUxYThlZDNiZGRjY2FkMDExNmVhNzQ5NjhmYTcxMWRlNjYxNzc0MmQzOGMxZWZjOWM0OWQ3Y2E5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.VRSfimqz06FaB8o1iuIrmHA2OW4I19CRc8WjmUBB3kk)
> 
> 程序内编号： ![屏幕截图 2024-06-26 134542](https://private-user-images.githubusercontent.com/145087619/343023511-5cda9979-c1f3-4e32-8dcf-0f7515e0401b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0NDcxMTcsIm5iZiI6MTcxOTQ0NjgxNywicGF0aCI6Ii8xNDUwODc2MTkvMzQzMDIzNTExLTVjZGE5OTc5LWMxZjMtNGUzMi04ZGNmLTBmNzUxNWUwNDAxYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyN1QwMDA2NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNTRhMjVlZmIzMmRhNmQ3YTI1OTEyMGY1N2E3MzdlNjQ1YjMxOGI4NGMxMzI5NTk1YTU1ZmI2YmMzOTRlNDEyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.pYr4YAVnXJuZNTkXpXu6fOnrPak3ypW3k_A1m3AQ6fs)

谢谢🙏有效果了

**Comment by T1de2077** [comment]
> 1.可能你自己训练的模型参数量不够 2.你的模型里标签类型名应该和程序的一致（好像头是0，身体是1我没仔细看） 另外你的comment会被所有关注此issue的人收到，你不需要发两次

侧键开关可以更改为鼠标前侧键吗？后侧键有点用不习惯

**Comment by Passer1072** [comment]
> > 1.可能你自己训练的模型参数量不够2.你的模型里标签类型名应该和程序的一致（好像头是0，身体是1我没仔细看）另外你的评论会被所有关注此issue的人收到，你不需要发两次
> 
> 侧键可以点击前侧键吗？后侧键用不习惯

将代码内所有0x05改为0x04即可

0x01：左键
0x02：右键
0x03：中键（滚轮）
0x04：鼠标侧键 2（通常是“后退”按钮）
0x05：鼠标侧键 1（通常是“前进”按钮）

**Comment by T1de2077** [comment]
> > > 1.可能你自己训练的模型参数量不够2.你的模型里标签类型名应该和程序的一致（好像头是0，身体是1我没仔细看）另外你的评论会被所有关注此issue的人收到，你不需要发两次
> > 
> > 
> > 侧键可以点击前侧键吗？ 后侧键用不习惯
> 
> 将代码内所有0x05改为0x04即可
> 
> 0x01：左键 0x02：右键 0x03：中键（滚轮） 0x04：鼠标侧键 2（通常是“后退”按钮） 0x05：鼠标侧键 1（通常是“前进”按钮）

🙏明白了哥

**Comment by molanp** [comment]
建议使用管理员运行脚本来避免无法操作以管理员运行的游戏
