### ISSUE TITLE
鼠标无法移动解决办法

### ISSUE THREAD

**Issue by greenhandBen** [Passer1072/RookieAI_yolov8#22]
使用DD驱动键鼠，github即可下载。

**Comment by greenhandBen** [comment]
导入dll后
将win32api.mouse_event改成dd_dll.DD_movR
但测试下来号没了，容易拉闸。
之前用自己写的YOLO自瞄没事
但这套源码就拉闸了

**Comment by Passer1072** [comment]
> 导入dll后
> 
> 将win32api.mouse_event改成dd_dll.DD_movR
> 
> 但测试下来号没了，容易拉闸。
> 
> 之前用自己写的YOLO自瞄没事
> 
> 但这套源码就拉闸了

收到，请问是在什么游戏拉闸的，win32在国产游戏特别容易拉闸是真的，在开发的新版本可以选择移动方式我会尽快发布。

**Comment by sorbet-TT** [comment]
> > 导入dll后
> > 将win32api.mouse_event改成dd_dll.DD_movR
> > 但测试下来号没了，容易拉闸。
> > 之前用自己写的YOLO自瞄没事
> > 但这套源码就拉闸了
> 
> 收到，请问是在什么游戏拉闸的，国产游戏特别容易拉闸是真的，在开发的新版本可以选择移动方式我会尽快发布。我自己玩的外服也都没事。

的确封的快，我换成罗技移动XF玩个10几局没啥事，下线5-6小时在上线就十年了 像卡拉 XFHD 三角洲行动都会，外服apex pubg 不羁联盟我5月22号玩到现在也没封。

**Comment by Passer1072** [comment]
> > > 导入dll后
> 
> > > 将win32api.mouse_event改成dd_dll.DD_movR
> 
> > > 但测试下来号没了，容易拉闸。
> 
> > > 之前用自己写的YOLO自瞄没事
> 
> > > 但这套源码就拉闸了
> 
> > 
> 
> > 收到，请问是在什么游戏拉闸的，国产游戏特别容易拉闸是真的，在开发的新版本可以选择移动方式我会尽快发布。我自己玩的外服也都没事。
> 
> 
> 
> 的确封的快，我换成罗技移动XF玩个10几局没啥事，下线5-6小时在上线就十年了 像卡拉 XFHD 三角洲行动都会，外服apex pubg 不羁联盟我5月22号玩到现在也没封。

国服我觉得没有很稳定的方法，听他们说国服kmbox也没搞，所以国服我也不知道怎么办。

**Comment by greenhandBen** [comment]
> > 导入dll后
> > 将win32api.mouse_event改成dd_dll.DD_movR
> > 但测试下来号没了，容易拉闸。
> > 之前用自己写的YOLO自瞄没事
> > 但这套源码就拉闸了
> 
> 收到，请问是在什么游戏拉闸的，国产游戏特别容易拉闸是真的，在开发的新版本可以选择移动方式我会尽快发布。我自己玩的外服也都没事。

玩的是国服的无畏契约，老哥代码写得真挺好的，用着非常舒服。

**Comment by Passer1072** [comment]
> > > 导入dll后
> 
> > > 将win32api.mouse_event改成dd_dll.DD_movR
> 
> > > 但测试下来号没了，容易拉闸。
> 
> > > 之前用自己写的YOLO自瞄没事
> 
> > > 但这套源码就拉闸了
> 
> > 
> 
> > 收到，请问是在什么游戏拉闸的，国产游戏特别容易拉闸是真的，在开发的新版本可以选择移动方式我会尽快发布。我自己玩的外服也都没事。
> 
> 
> 
> 玩的是国服的无畏契约，老哥代码写得真挺好的，用着非常舒服。

国服瓦容易拉闸吧，用多久了真没问题吗？最近我也想在国服瓦试试。
