### ISSUE TITLE
运行报错json多个错误

### ISSUE THREAD

**Issue by NIKTY826** [Passer1072/RookieAI_yolov8#23]
首先谢谢大佬分享，教程很详细，小白搭建成功也打包好了，运行出现代码错误是怎么回事呢，跪求大佬解答！
![Uploading 11.png…]()

**Comment by Passer1072** [comment]
> 首先谢谢大佬分享，教程很详细，小白搭建成功也打包好了，运行出现代码错误是怎么回事呢，跪求大佬解答！
> 
> ![Uploading 11.png…]()
> 
> 

您上传的图片看不见请重新上传

**Comment by NIKTY826** [comment]
谢谢大佬，反复钻研仓库，成功打包并且运行了！就是启动很慢，需要1分钟到达界面，这个是什么原因呢？
还有就是我pubg用了5W的模型，参数调整有没有什么建议，只能预瞄前两发子弹后面直接上天了

**Comment by Passer1072** [comment]
> 谢谢大佬，反复钻研仓库，成功打包并且运行了！就是启动很慢，需要1分钟到达界面，这个是什么原因呢？ 还有就是我pubg用了5W的模型，参数调整有没有什么建议，只能预瞄前两发子弹后面直接上天了

无法确定启动慢的原因，我发布了新版本可以再试试。游戏运行时AI推理多少FPS？在游戏运行时查看AI的推理帧数是否很低导致锁不住目标，如果推理FPS低于30考虑降低游戏画质加锁帧保证AI算力充足。

**Comment by NIKTY826** [comment]
新版本打包后，运行出现No module named 'onnxruntime，33行这个，这行代码删了也不行，是啥原因呢，库我是按照全部复制的方法粘贴过去的

**Comment by Passer1072** [comment]
> 新版本打包后，运行出现No module named 'onnxruntime，33行这个，这行代码删了也不行，是啥原因呢，库我是按照全部复制的方法粘贴过去的

去掉33行后不应该再有报错，如果依然报错尝试install一个onnxruntime库，这个库目前没有用到只是开头导入了。
