### ISSUE TITLE
鼠标移动卡顿

### ISSUE THREAD

**Issue by NovaShen555** [Passer1072/RookieAI_yolov8#24]
勉强能朝着目标移动，但是十分卡顿，相当于每秒3帧，移动三次，而且移动非常跳跃
请问是什么情况呢
3060ti 罗技g304

**Comment by NovaShen555** [comment]
我使用其他的project的时候也是遇到了相同的问题，应该是某个固定的东西导致的

**Comment by NovaShen555** [comment]
> 呢

gpu有占用，37%左右，关闭程序后无占用

**Comment by Passer1072** [comment]
> > 呢
> 
> gpu有占用，37%左右，关闭程序后无占用

单独运行ai时FPS显示多少？游戏需要降低画质加锁帧尽可能为AI留出算力来保证AI推理帧数。

**Comment by NovaShen555** [comment]
已经搞明白了，确实是因为算力的问题 sor
现在的情况是，apex占用60%，ai占用20%，还有20%闲置算力并未被ai利用
单独开启ai时ai也只可以占用到80%，这是由于某种系统级的限制还是什么原因呢

**Comment by Passer1072** [comment]
> 已经搞明白了，确实是因为算力的问题 sor
> 
> 现在的情况是，apex占用60%，ai占用20%，还有20%闲置算力并未被ai利用
> 
> 单独开启ai时ai可以占用到80%，这是由于某种系统级的限制还是什么原因呢

初步判断是显卡算力或带宽限制，这个问题我也有，除了限制游戏的占用没有更好的解决办法。

**Comment by molanp** [comment]
V3开发版解决

**Comment by Passer1072** [comment]
> 勉强能朝着目标移动，但是十分卡顿，相当于每秒3帧，移动三次，而且移动非常跳跃
> 
> 请问是什么情况呢
> 
> 3060ti 罗技g304

请将apex的画质调到最低为ai留出算力，开1080P不要用2K，使用atlas游戏系统。占用不完全是因为受限于显卡带宽与算力，加上目前版本优化差，可以等3.0会有些优化。
