### ISSUE TITLE
实时fps偏低，cpu和gpu的占用只有10%左右

### ISSUE THREAD

**Issue by zxtznb** [Passer1072/RookieAI_yolov8#30]
谢谢大佬分享，我按教程搭建成功也打包好了。但是我的实时fps一直在17-19徘徊，出去看任务管理器cpu和gpu的占用只有10%左右。

![Screenshot 2024-07-07 095120](https://github.com/Passer1072/RookieAI_yolov8/assets/136035740/23774159-302e-405a-90c9-c0add230e5da)

然后我安装了CUDA和pytorch，但是仍然只有17帧左右。这是什么原因？我在打包后启动exe程序时出现了 “AttributeError: ‘DXCamera‘ object has no attribute ‘is_capturing‘” 的错误，通过修改图形设置，将首选图形处理器设置成了核显才能正常启动，是这个原因造成fps偏低的吗？

**Comment by Passer1072** [comment]
> 谢谢大佬分享，我按教程搭建成功也打包好了。但是我的实时fps一直在17-19徘徊，出去看任务管理器cpu和gpu的占用只有10%左右。
> 
> ![Screenshot 2024-07-07 095120](https://private-user-images.githubusercontent.com/136035740/346306935-23774159-302e-405a-90c9-c0add230e5da.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAzMTkxMjgsIm5iZiI6MTcyMDMxODgyOCwicGF0aCI6Ii8xMzYwMzU3NDAvMzQ2MzA2OTM1LTIzNzc0MTU5LTMwMmUtNDA1YS05MGM5LWMwYWRkMjMwZTVkYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwN1QwMjIwMjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZDY1MjhlMzZkODNmNDEwODEzOTA2NTM0ZjEzMGM0OTAzNmQwNTlkNjJhZDkxZjgwNTRlZGMzZDllNGM3NDMyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.yn952_R9FABtFP9IU4QF-Z5QC5o4eUoaj7EUcXMPqkU)
> 
> 然后我安装了CUDA和pytorch，但是仍然只有17帧左右。这是什么原因？我在打包后启动exe程序时出现了 “AttributeError: ‘DXCamera‘ object has no attribute ‘is_capturing‘” 的错误，通过修改图形设置，将首选图形处理器设置成了核显才能正常启动，是这个原因造成fps偏低的吗？

您是什么显卡？建议现在IDE内测试无问题后再打包。显卡推荐RTX3060以上。
通过pip list 查看安装的Pytorch版本后缀是否带有+CU的字样，+CU的版本才是支持CUDA加速推理的版本，+CPU版本是错误的，正确的如图：
![屏幕截图 2024-07-07 110028](https://github.com/Passer1072/RookieAI_yolov8/assets/145087619/91d8319d-6426-4dd5-b08c-e79c19c39c4b)
关于报错：检查你的Python环境建议使用和我一样的Python3.9版本，DXcam对高版本Python兼容不佳，或者尝试使用[V2.4.3.3(beta)](https://github.com/Passer1072/RookieAI_yolov8/tree/main/Beta/V2.4.3(beta))版本并在配套[settings.json](https://github.com/Passer1072/RookieAI_yolov8/blob/main/Beta/V2.4.3(beta)/settings.json)中设置`"deactivate_dxcam": true`，这样可以禁用加载dxcam模块解决一些问题。
玩游戏时将游戏画质尽可能降低画质并且锁帧，为Ai预留算力。

**Comment by zxtznb** [comment]
我的显卡是GTX 1650，Pytorch版本是正确的。

![Screenshot 2024-07-07 204642](https://github.com/Passer1072/RookieAI_yolov8/assets/136035740/a5b394dd-769a-4dfd-97aa-ea32fd7e085e)

是因为我的显卡太老了吗？我不太了解显卡，我以为cpu和gpu占用没吃满就能提升fps，我宁愿它占用高一点。
我将python版本降到了3.9，使用V2.4.3.3(beta)版本还是出现了DXcam报错，禁用加载dxcam后实时fps没有提升。

![Screenshot 2024-07-07 211034](https://github.com/Passer1072/RookieAI_yolov8/assets/136035740/8c851c9d-a3ad-44da-b6c7-e34ec8f5931d)
![Screenshot 2024-07-07 211409](https://github.com/Passer1072/RookieAI_yolov8/assets/136035740/57c2e5fc-24f9-472e-ad5d-08d3d3411751)

**Comment by Passer1072** [comment]
> 我的显卡是 GTX 1650，Pytorch版本正确。
> 
> ![截图 2024-07-07 204642](https://private-user-images.githubusercontent.com/136035740/346335532-a5b394dd-769a-4dfd-97aa-ea32fd7e085e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAzNTk4MTksIm5iZiI6MTcyMDM1OTUxOSwicGF0aCI6Ii8xMzYwMzU3NDAvMzQ2MzM1NTMyLWE1YjM5NGRkLTc2OWEtNGRmZC05N2FhLWVhMzJmZDdlMDg1ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwN1QxMzM4MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZDg1ZDZjYTBiNmExOWZiMDEwYTM3YWZlM2Y1MDM5MTg1ZWRjNTUwNDQ0MjMxMDk0MmYxMDIwNmI2MWZiMjZiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xEfMPpFmmwbZtZZkFVghR1qOwAv-iKDCA00JwNPitUU)
> 
> 因为我的显卡太老了吗？我不太了解显卡，以为cpu和gpu占用没吃满就能提升fps，我宁愿它占用高一点。 我将python版本降到了3.9，使用V2.4.3.3(beta)版本仍然出现了DXcam报错，禁用加载dxcam后实时fps没有提升。
> 
> ![截图 2024-07-07 211034](https://private-user-images.githubusercontent.com/136035740/346337091-8c851c9d-a3ad-44da-b6c7-e34ec8f5931d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAzNTk4MTksIm5iZiI6MTcyMDM1OTUxOSwicGF0aCI6Ii8xMzYwMzU3NDAvMzQ2MzM3MDkxLThjODUxYzlkLWEzYWQtNDRkYS1iNmM3LWUzNGVjOGY1OTMxZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwN1QxMzM4MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYjA1MjEzZDRkODM5N2IxZDc2NDRjMzA5ZmMzMmQwNzQ2Yzk1MGE5Zjk5YzMzYWJlZTkwMzMxNjcyZTVmODc4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.woQJLOg2ghybC0bVz9hUCfCFigaTH7RLENC5DOPCd8I) ![截图 2024-07-07 211409](https://private-user-images.githubusercontent.com/136035740/346337277-57c2e5fc-24f9-472e-ad5d-08d3d3411751.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAzNTk4MTksIm5iZiI6MTcyMDM1OTUxOSwicGF0aCI6Ii8xMzYwMzU3NDAvMzQ2MzM3Mjc3LTU3YzJlNWZjLTI0ZjktNDcyZS1hZDVkLTA4ZDNkMzQxMTc1MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwN1QxMzM4MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNjFkZjdjNjY5N2ViODBhYzdkMzM5N2E3Mzk1NDM0ZjVjYmNlNmVlNDg1MTY3NzQ3NDUwYzYxYWEzMTJmYTA0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.HRbKSGslcGNIawLfcNfe6AY65DoqT529EgIX3H7EwyI)

你的环境没有问题，确实是显卡太老了，1650的算力不适合跑Ai项目，游戏和Ai同时开更吃不消了。由于算力和贷款原因导致的GPU占用不满这个没有办法解决，可以尝试使用YOLOv5的AI项目会好些。

**Comment by zxtznb** [comment]
好的，谢谢大佬
