### ISSUE TITLE
为啥呀，显卡3070ti

### ISSUE THREAD

**Issue by lovefan-fan** [Passer1072/RookieAI_yolov8#33]
随机特征码: -3922980700769024791
开始加载飞易来盒子文件...
启动飞易来盒子...
open handle = 18446744073709551615
鼠标移动:False
启动盒子失败
Loading prefix variables...
前置变量加载成功！
开始获取公告......
获取成功
开始获取版本号......
获取成功
[WARNING] 设置文件中的模型文件路径无效; 使用默认模型文件
加载模型文件: yolov8n.pt
开始获取版本号......
获取成功
Loading settings...
设置加载成功！
update_values function was called（配置已更新）
正在等待加载完成
[INFO]已禁用DXcam
Ultralytics YOLOv8.2.54 🚀 Python-3.9.13 torch-2.2.0+cpu 
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\fan\.pyenv\pyenv-win\versions\3.9.13\lib\threading.py", line 980, in _bootstrap_inner
    self.run()
  File "C:\Users\fan\.pyenv\pyenv-win\versions\3.9.13\lib\threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "E:\ruanjian\RookieAI_yolov8-main\RookieAI_YOLOv8_V2.4.3.py", line 1978, in main_program_loop
    results = model.predict(frame, save=False, conf=confidence, half=True, agnostic_nms=True, iou=0.7
  File "E:\ruanjian\RookieAI_yolov8-main\venv\lib\site-packages\ultralytics\engine\model.py", line 435, in predict
    self.predictor.setup_model(model=self.model, verbose=is_cli)
  File "E:\ruanjian\RookieAI_yolov8-main\venv\lib\site-packages\ultralytics\engine\predictor.py", line 305, in setup_model
    device=select_device(self.args.device, verbose=verbose),
  File "E:\ruanjian\RookieAI_yolov8-main\venv\lib\site-packages\ultralytics\utils\torch_utils.py", line 137, in select_device
    raise ValueError(
ValueError: Invalid CUDA 'device=0' requested. Use 'device=cpu' or pass valid CUDA device(s) if available, i.e. 'device=0' or 'device=0,1,2,3' for Multi-GPU.

torch.cuda.is_available(): False
torch.cuda.device_count(): 0
os.environ['CUDA_VISIBLE_DEVICES']: None
See https://pytorch.org/get-started/locally/ for up-to-date torch install instructions if no CUDA devices are seen by torch.

**Comment by Passer1072** [comment]
> 随机特征码: -3922980700769024791
> 
> 开始加载飞易来盒子文件...
> 
> 启动飞易来盒子...
> 
> open handle = 18446744073709551615
> 
> 鼠标移动:False
> 
> 启动盒子失败
> 
> Loading prefix variables...
> 
> 前置变量加载成功！
> 
> 开始获取公告......
> 
> 获取成功
> 
> 开始获取版本号......
> 
> 获取成功
> 
> [WARNING] 设置文件中的模型文件路径无效; 使用默认模型文件
> 
> 加载模型文件: yolov8n.pt
> 
> 开始获取版本号......
> 
> 获取成功
> 
> Loading settings...
> 
> 设置加载成功！
> 
> update_values function was called（配置已更新）
> 
> 正在等待加载完成
> 
> [INFO]已禁用DXcam
> 
> Ultralytics YOLOv8.2.54 🚀 Python-3.9.13 torch-2.2.0+cpu 
> 
> Exception in thread Thread-1:
> 
> Traceback (most recent call last):
> 
>   File "C:\Users\fan\.pyenv\pyenv-win\versions\3.9.13\lib\threading.py", line 980, in _bootstrap_inner
> 
>     self.run()
> 
>   File "C:\Users\fan\.pyenv\pyenv-win\versions\3.9.13\lib\threading.py", line 917, in run
> 
>     self._target(*self._args, **self._kwargs)
> 
>   File "E:\ruanjian\RookieAI_yolov8-main\RookieAI_YOLOv8_V2.4.3.py", line 1978, in main_program_loop
> 
>     results = model.predict(frame, save=False, conf=confidence, half=True, agnostic_nms=True, iou=0.7
> 
>   File "E:\ruanjian\RookieAI_yolov8-main\venv\lib\site-packages\ultralytics\engine\model.py", line 435, in predict
> 
>     self.predictor.setup_model(model=self.model, verbose=is_cli)
> 
>   File "E:\ruanjian\RookieAI_yolov8-main\venv\lib\site-packages\ultralytics\engine\predictor.py", line 305, in setup_model
> 
>     device=select_device(self.args.device, verbose=verbose),
> 
>   File "E:\ruanjian\RookieAI_yolov8-main\venv\lib\site-packages\ultralytics\utils\torch_utils.py", line 137, in select_device
> 
>     raise ValueError(
> 
> ValueError: Invalid CUDA 'device=0' requested. Use 'device=cpu' or pass valid CUDA device(s) if available, i.e. 'device=0' or 'device=0,1,2,3' for Multi-GPU.
> 
> 
> 
> torch.cuda.is_available(): False
> 
> torch.cuda.device_count(): 0
> 
> os.environ['CUDA_VISIBLE_DEVICES']: None
> 
> See https://pytorch.org/get-started/locally/ for up-to-date torch install instructions if no CUDA devices are seen by torch.

你的Pytorch版本为CPU版本，需要重新下载GPU版本的Pytorch

**Comment by molanp** [comment]
请安装对应版本的cuda驱动
[https://developer.nvidia.com/cuda-toolkit-archive](https://developer.nvidia.com/cuda-toolkit-archive)
