### ISSUE TITLE
[Question]全局变量

### ISSUE THREAD

**Issue by molanp** [Passer1072/RookieAI_yolov8#34]
代码里哪些全局变量是从设置中读取的
读取设置所赋值变量有些混乱
我正在进行设置读取设置以及可读性的大规模重构与优化
请提供相关信息
- `xxx_var`和`xxx`有什么区别
- `load_prefix`函数能否省略
- 全局设置初始化设置变量能否删除，哪些不能删除
- more...

**Comment by Passer1072** [comment]
> 代码里哪些全局变量是从设置中读取的 读取设置所赋值变量有些混乱 我正在进行设置读取设置以及可读性的大规模重构与优化 请提供相关信息
> 
> * `xxx_var`和`xxx`有什么区别
> * `load_prefix`函数能否省略
> * 全局设置初始化设置变量能否删除，哪些不能删除
> * more...

感谢您对代码进行重构与优化！
不得不承认由于我是第一次编写这种体量的代码且还在学习阶段，没有学习和制定系统性的命名规则导致各种变量名混乱难以理解，我对此感到抱歉，我会尽可能回答您的问题并向您解释我代码中各个变量的命名问题。
`xxx_var`和`xxx`有什么区别：
`xxx_var`早期我一般用于命名 GUI 控件的变量，在GUI控件受到任何更改时调用`def update_values(*args)`函数，通过获取GUI控件的值（也就是获取`xxx_var`）并将其赋值给名字相同但不带后缀`_var`的变量以供后面使用。但是在后面也渐渐没有遵从这个规则。
`load_prefix`函数能否省略：
这个函数我用于加载前置变量，也就是提前加载一些必须在GUI生成前就加载的开关功能函数，例如“禁止联网加载公告开关”、“随机软件标题开关”等，有时候做新功能测试也有一些用，我认为不能省略。
全局设置初始化设置变量能否删除，哪些不能删除：
除计时器、飞易来U盘设置、# 目标列表、# 人体示意图、软件页面调整等用于方便调整和新功能测试用的变量外，其他的已完善的功能的全局设置初始化可以删除不影响使用，但是我认为删不删影响不大，这部分也可以当作后续如果忘了某个变量的意义可以来这里查看。
