### ISSUE TITLE
FPS问题与其他设置选项的BUG

### ISSUE THREAD

**Issue by wdkflag** [Passer1072/RookieAI_yolov8#38]
![PixPin_2024-07-15_20-12-43](https://github.com/user-attachments/assets/8507e5b5-0a05-493a-9e0f-f940f41e98ac)

  无法保存设置更换模型等，只能在配置文件更改，如果全都重新安装的话是正常的，但一旦更改设置或者更换模型后保存设置重启，就会出现这个bug不知道我是不是个例望解答！
  FPS只有30左右，在我的3050ti上面始终占用gpu为50%左右，可以可以优化一下让他能够吃满，因为我是双电脑用另一台电脑打游戏，这台的话就直接让他吃满就行这样fps也能更高，或者作者愿意的话再优化一下代码，能够得到更高的fps，又或者加入比如yolov5模型和其他格式的模型文件的支持！
  谢谢！

**Comment by Passer1072** [comment]
> ![PixPin_2024-07-15_20-12-43](https://github.com/user-attachments/assets/8507e5b5-0a05-493a-9e0f-f940f41e98ac)
> 
> 
> 
> 
> 
>   无法保存设置更换模型等，只能在配置文件更改，如果全都重新安装的话是正常的，但一旦更改设置或者更换模型后保存设置重启，就会出现这个bug不知道我是不是个例望解答！
> 
>   FPS只有30左右，在我的3050ti上面始终占用gpu为50%左右，可以可以优化一下让他能够吃满，因为我是双电脑用另一台电脑打游戏，这台的话就直接让他吃满就行这样fps也能更高，或者作者愿意的话再优化一下代码，能够得到更高的fps，又或者加入比如yolov5模型和其他格式的模型文件的支持！
> 
>   谢谢！

已注意到这个问题，是因为最近README文件格式更改导致的，我将在晚些时候修复。

**Comment by wdkflag** [comment]
> > ![PixPin_2024-07-15_20-12-43](https://private-user-images.githubusercontent.com/117509335/348699450-8507e5b5-0a05-493a-9e0f-f940f41e98ac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwNDc5MDUsIm5iZiI6MTcyMTA0NzYwNSwicGF0aCI6Ii8xMTc1MDkzMzUvMzQ4Njk5NDUwLTg1MDdlNWI1LTBhMDUtNDkzYS05ZTBmLWY5NDBmNDFlOThhYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNVQxMjQ2NDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNDYzOGEwMmMxZWFiMDNmZmQyNjI4ODdlYzFiZmIyODY4YmNjZjAwZWVkNDFjNjQyZjI4NTI5OGFiZDVjNDJlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Dq6fZkMCXnZOgAKwzG8XjrOKvdmIyrzvw4pxqtu8bQY)
> > 无法设置更换模型等，只能在配置文件中，如果全都重新安装的话是正常的，但一旦设置或者更换模型后设置重新启动，就会出现这个bug不知道我是不是个例！
> > FPS只有30左右，在我的3050ti上面始终占用gpu为50%左右，可以可以优化一下让他能够吃满，因为我是双电脑用另一台电脑打游戏，这台的话就直接让他吃满就这样fps也能更高，或者作者愿意的话再优化一下代码，能够得到更高的fps，又或者加入比如yolov5模型和其他格式的模型文件支持！
> > 谢谢！
> 
> 已注意到这个问题，因为最近README文件系统更改会导致的，我将在必要时修复。

希望可以解决一下FPS的问题，能不能让性能更好点！ 谢谢

**Comment by Passer1072** [comment]
README问题已暂时修复，关于优化问题已在计划中
