### ISSUE TITLE
自己训练模型的一些参数问题

### ISSUE THREAD

**Issue by qq846511277** [Passer1072/RookieAI_yolov8#4]
需要几个标签？ 就0：头 1：身子

**Comment by LaxdalGe** [comment]
Arduino模式进展怎么样了？是把Arduino当作类kmbox的硬件来转接鼠标吗？

**Comment by lovefan-fan** [comment]
> > 需要几个标签？ 就0：头 1：身子
> 
> 看你自己的需求了，短ttk建议头身，长ttk例如apex敌我就可以

当自己训练的模型有多个标签时，只用修改代码中这处就可以了么

# 目标列表
target_mapping = {'敌人': 0, '倒地': 1, '队友': 2,}

**Comment by Passer1072** [comment]
> > > 需要几个标签？ 就0：头 1：身子
> > 
> > 
> > 看你自己的需求了，短ttk建议头身，长ttk例如apex敌我就可以
> 
> 当自己训练的模型有多个标签时，只用修改代码中这处就可以了么
> 
> # 目标列表
> target_mapping = {'敌人': 0, '倒地': 1, '队友': 2,}

是的，例如原本为：
`# 目标列表
target_mapping = {'敌人': 0, '倒地': 1, '队友': 2}`
模型有更多标签可以修改为：
`# 目标列表
target_mapping = {'敌人': 0, '倒地': 1, '队友': 2, '测试': 3}`
