### ISSUE TITLE
[Feature]加个键盘上的键吧...

### ISSUE THREAD

**Issue by molanp** [Passer1072/RookieAI_yolov8#44]
**Is your feature request related to a problem? Please describe.**

**您的功能请求是否与某个问题相关？请描述清楚**

None

**Describe the features you need to add.**

**描述您希望增加的功能**

关于自瞄的触发按键，希望增加个键盘上的按键以便映射，一般建议为`Ctrl`按键(左)

**Describe alternatives you've considered**

**描述您考虑过的任何备选解决方案或功能**

尝试增加键扫描码，但程序不能很好工作，ui也阻塞了

**Comment by Relief156** [comment]
我感觉这个改 应该问题不大
