### ISSUE TITLE
可以出一个本地运行的教程嘛～

### ISSUE THREAD

**Issue by yxplus1116** [Passer1072/RookieAI_yolov8#5]

**Comment by yxplus1116** [comment]
我的模型是 cf 模型ONNX格式的，不知道能不能用来识别 cf

**Comment by Passer1072** [comment]
> 我的模型是cf模型ONNX格式的，不知道能不能用来识别cf

不可以，目前只支持*.pt格式的模型。软件打包到本地的教程已经写在使用方法里了，哪里不会或者有问题可以问我  :)

**Comment by yxplus1116** [comment]
> > 我的模型是cf模型ONNX格式的，不知道能不能用来识别cf
> 
> 不可以，目前只支持*.pt格式的模型。软件打包到本地的教程已经写在使用方法里了，哪里不会或者有问题可以问我 :)

我想在本地把代码跑起来，可以加个联系方式吗 :)

**Comment by yxplus1116** [comment]
> > 我的模型是cf模型ONNX格式的，不知道能不能用来识别cf
> 
> 不可以，目前只支持*.pt格式的模型。软件打包到本地的教程已经写在使用方法里了，哪里不会或者有问题可以问我 :)
感谢你。 请问这个对 Python 和 pip 的版本有要求吗？我想在本地运行起来

**Comment by yxplus1116** [comment]
> > 我的模型是cf模型ONNX格式的，不知道能不能用来识别cf
> 
> 不可以，目前只支持*.pt格式的模型。软件打包到本地的教程已经写在使用方法里了，哪里不会或者有问题可以问我 :)

感谢你。 请问这个对 Python 和 pip 的版本有要求吗？我想在本地运行起来

**Comment by Passer1072** [comment]
> > > 我的模型是cf模型ONNX格式的，不知道能不能用来识别cf
> > 
> > 
> > 不可以，目前只支持*.pt格式的模型。软件备份到本地的教程已经写在使用方法里了，哪里不会或者有问题可以问我:)
> 
> 谢谢你。请问这个对Python和pip的版本有要求吗？我想在本地运行起来

我使用的Python3.9，3.10好像打包会出问题。如果别的Python版本有问题可以跟我用一样的3.9
对pip没有要求，对某些库的版本有强制要求

需要用到的库已经列举在requirements.txt里了，可以`pip install -r requirements.txt`直接获取，Pytorch版本可根据自己需求下载我这里使用的：
`pip install torch==2.2.0 torchvision==0.17.0 torchaudio==2.2.0 --index-url https://download.pytorch.org/whl/cu121
`
只支持NV显卡

希望这些能帮到你

**Comment by yxplus1116** [comment]
> > > > 我的模型是cf模型ONNX格式的，不知道能不能用来识别cf
> > > 
> > > 
> > > 不可以，目前只支持*.pt格式的模型。软件备份到本地的教程已经写在使用方法里了，哪里不会或者有问题可以问我:)
> > 
> > 
> > 谢谢你。请问这个对Python和pip的版本有要求吗？我想在本地运行起来
> 
> 我使用的Python3.9，3.10好像打包会出问题。如果别的Python版本有问题可以跟我用一样的3.9 对pip没有要求，对某些库的版本有强制要求
> 
> 需要用到的库已经列举在requirements.txt里了，可以`pip install -r requirements.txt`直接获取，Pytorch版本可根据自己需求下载我这里使用的： `pip install torch==2.2.0 torchvision==0.17.0 torchaudio==2.2.0 --index-url https://download.pytorch.org/whl/cu121 ` 只支持NV显卡
> 
> 希望这些能帮到你

好的.再次感谢你。
有问题再向您提 issues :)
