### ISSUE TITLE
大佬你好，请问支持AMD显卡吗

### ISSUE THREAD

**Issue by kuailedeskwkd** [Passer1072/RookieAI_yolov8#50]
如果不支持，可以使用CPU部署进行吗？这样性能损失大吗？或者支持p106进行单独处理？
不考虑使用AMD进行模型训练，只进行使用，谢谢。

**Comment by Passer1072** [comment]
不推荐使用CPU进行推理，CPU推理速度太慢几乎不可用，但是油管有使用一些AMD官方插件可以模拟运行CUDA，这样可能比CPU更好，但是我没有AMD显卡你可以尝试一下。

**Comment by molanp** [comment]
#58
