### ISSUE TITLE
nameerror:name 'name is not defined 

### ISSUE THREAD

**Issue by chengzhi0916** [Passer1072/RookieAI_yolov8#52]
![1](https://github.com/user-attachments/assets/7e2b021d-f191-4be6-af97-dd9915a7fdd0)

**Comment by chengzhi0916** [comment]
求助 挣了俩小时了还是没解决

**Comment by molanp** [comment]
如果只是本地运行，不需要分发，请不要使用pyinstaller打包
详参阅文档中的开发者部分

**Comment by Passer1072** [comment]
> ![1](https://private-user-images.githubusercontent.com/33573979/359381530-7e2b021d-f191-4be6-af97-dd9915a7fdd0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2MTE0MDcsIm5iZiI6MTcyNDYxMTEwNywicGF0aCI6Ii8zMzU3Mzk3OS8zNTkzODE1MzAtN2UyYjAyMWQtZjE5MS00YmU2LWFmOTctZGQ5OTE1YTdmZGQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI1VDE4MzgyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgyZDcxZDUwNWRjZDE3ZDVkNGYzZDNjZDYwYzE3MzdkNTQ0OTNjOGU5MDYyYWE4YjUyYzE4ODcyMWQ4MjBkNGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0SSqxiHp27x_nFglWFbBH8nxIgxOlxXA3auB-8EKxII)

无法准确定位到问题，建议尝试最新的Beta版或使用`RookieAI_YOLOv8_V2.4.3.py`稳定版，先在IDE内调试完毕再打包。

**Comment by Passer1072** [comment]
> ![1](https://private-user-images.githubusercontent.com/33573979/359381530-7e2b021d-f191-4be6-af97-dd9915a7fdd0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2MTE0MDcsIm5iZiI6MTcyNDYxMTEwNywicGF0aCI6Ii8zMzU3Mzk3OS8zNTkzODE1MzAtN2UyYjAyMWQtZjE5MS00YmU2LWFmOTctZGQ5OTE1YTdmZGQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI1VDE4MzgyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgyZDcxZDUwNWRjZDE3ZDVkNGYzZDNjZDYwYzE3MzdkNTQ0OTNjOGU5MDYyYWE4YjUyYzE4ODcyMWQ4MjBkNGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0SSqxiHp27x_nFglWFbBH8nxIgxOlxXA3auB-8EKxII)

无法准确定位到问题，建议尝试最新的Beta版或使用`RookieAI_YOLOv8_V2.4.3.py`稳定版，先在IDE内调试完毕再打包。
