### ISSUE TITLE
关于帧数的一些问题求助

### ISSUE THREAD

**Issue by NathanielChenZY** [Passer1072/RookieAI_yolov8#54]
在运行最新版和v2.4.3的过程中，本地运行后（pt模型），如果不开启游戏的话，帧数维持在60帧左右，但进入游戏后在大厅还好，一旦进入靶场，帧数会直接变成个位数，甚至0帧，但是没有报错，无法找到原因，麻烦各位大佬提供一下帮助

**Comment by NathanielChenZY** [comment]
> > 在运行最新版和v2.4.3的过程中，本地运行后（pt模型），如果不开启游戏的话，帧数维持在60帧左右，但进入游戏后在大厅还好，一旦进入靶场，帧数会直接变成个位数，甚至0帧，但是没有报错，无法找到原因，麻烦各位大佬提供一下帮助
> 
> 
> 
> 游戏高占用导致AI获得的资源太少，建议将游戏的画质调到最低尽量降低显卡的占用，推荐使用独立的游戏系统可获得最好的效果。

感谢您的回复，我之前在使用2.4.3的时候完全没有任何问题（使用pt模型，帧数在ow2中为30-40，trt模型的话就帧数会有所上涨）。随后因为c盘爆红后，我删除了虚拟内存，就突然出现帧数问题，随后，我选择重装了包括cuda在内的整个环境，依然无法解决，今天将电脑重置后，问题依然存在，这是为什么啊🧐

**Comment by NathanielChenZY** [comment]
> > 在运行最新版和v2.4.3的过程中，本地运行后（pt模型），如果不开启游戏的话，帧数维持在60帧左右，但进入游戏后在大厅还好，一旦进入靶场，帧数会直接变成个位数，甚至0帧，但是没有报错，无法找到原因，麻烦各位大佬提供一下帮助
> 
> 
> 
> 游戏高占用导致AI获得的资源太少，建议将游戏的画质调到最低尽量降低显卡的占用，推荐使用独立的游戏系统可获得最好的效果。

之前删除虚拟内存后，帧数暴跌，有时候进程会卡死然后显示“cuda错误，无法访问指定内存”的报错

**Comment by Passer1072** [comment]
尝试过下载老版本吗？

**Comment by NathanielChenZY** [comment]
> 尝试过下载老版本吗？

因为使用2.4.3一直很稳定，所以就没有用老版本，就是删除虚拟内存后出现的问题😭

**Comment by NathanielChenZY** [comment]
![微信截图_20240826193925](https://github.com/user-attachments/assets/35f6b84e-626e-4a32-b8a5-ecec20a4beb3)
![微信截图_20240826193954](https://github.com/user-attachments/assets/fb62b494-48a3-4cfb-9e94-8fa1f94cf50e)

这是在游戏内打开菜单与关闭菜单的帧数对比

**Comment by NathanielChenZY** [comment]
问题已经解决，如果各位遇到与我一样的问题，解决方式如下：
1.查看cuda版本与torch版本是否一致，如果不一致请重新安装cuda或torch
2.查看cuda是否支持你的显卡
如果这两个有问题请重新安装cuda环境

如果还未解决请重装电脑
