### ISSUE TITLE
有偿找大佬求教使用方法

### ISSUE THREAD

**Issue by cccjk9527** [Passer1072/RookieAI_yolov8#55]
**Is your feature request related to a problem? Please describe.**

**您的功能请求是否与某个问题相关？请描述清楚**

Type here.

**Describe the features you need to add.**

**描述您希望增加的功能**

Type here.

**Describe alternatives you've considered**

**描述您考虑过的任何备选解决方案或功能**

Type here.

**Additional context**

在此处添加关于功能请求的任何其他上下文或截图

**Comment by chen870370470** [comment]
q208283091
