### ISSUE TITLE
使用飞易来出现准星乱飘的情况

### ISSUE THREAD

**Issue by z1braaa** [Passer1072/RookieAI_yolov8#62]
如题，对某些游戏来说win、mouse鼠标移动库失效后尝试飞易来，测试模拟压枪的时候发现鼠标每隔0.几秒向右向上偏离，是飞易来盒子版本的关系吗？

**Comment by Passer1072** [comment]
这是飞以来U盘的问题，之前我买的盗版飞易来就是这样，换了一个相对来说正版一些的就好了

z1braaa ***@***.***>于2024年10月17日 周四下午7:01写道：

**Comment by z1braaa** [comment]
请问佬的盒子版本是哪个？我是在某宝官方店铺买的6.8版本的，两个都是一样的情况

**Comment by z1braaa** [comment]
解决了，购买飞易来盒子的时候不要买最新版本的，买蓝色文盒即可
