### ISSUE TITLE
鼠标标准不符

### ISSUE THREAD

**Issue by ronme-ctrl** [Passer1072/RookieAI_yolov8#63]
鼠标移动不是直接向目标前进，而是一直沿着从光标位置到目标的角度移动。因此，标准不符合。光标会持续移动到屏幕边缘。请问有什么设置吗？

**Comment by molanp** [comment]
游戏窗口是否获得焦点

**Comment by ronme-ctrl** [comment]
在用鼠标点击以聚焦游戏窗口后，通过快捷键启动aim功能时，光标会持续向目标方向移动，并且会不停地移动到游戏窗口的屏幕边缘。请问有没有什么设置可以指定窗口的？

**Comment by molanp** [comment]
使用altab快捷键重新聚焦到游戏窗口呢

**Comment by ronme-ctrl** [comment]
我已经找到了问题的原因。系统显示的句柄值为18446744073709551615，且显示“鼠标移动：False”和“启动盒子失败”。看起来 x64_msdk.dll 文件似乎无效。请问有什么解决方案吗？


```
Python RookieAI_YOLOv8.py
开始加载飞易来盒子文件...
启动飞易来盒子...
open handle = 18446744073709551615
鼠标移动:False
启动盒子失败
Loading prefix variables...
前置变量加载成功！
开始获取公告......
获取成功
开始获取版本号......
获取成功
加载模型文件: yolov8n.pt
半精度推理 设置为: True
开始获取版本号......
获取成功
Loading settings...
设置加载成功！
update_values function was called（配置已更新）
正在等待加载完成
[INFO]已禁用DXcam
FPS: 0
FPS: 64
FPS: 61
```

**Comment by molanp** [comment]
此提示与问题产生无关

**Comment by Passer1072** [comment]
此软件只适用于FPS游戏（第一人称，例如Apex，CS等），不适用于MOBA等第三人称游戏。

ronme-ctrl ***@***.***>于2024年10月26日 周六下午1:16写道：

**Comment by molanp** [comment]
@Passer1072 请检查gmail收件箱，有事找
