### ISSUE TITLE
希望增加新的鼠标移动方法并可选

### ISSUE THREAD

**Issue by loy0516** [Passer1072/RookieAI_yolov8#64]
MOUSEEVENTF_MOVE = 0x0001
ctypes.windll.user32.mouse_event(MOUSEEVENTF_MOVE, x, y, 0, 0)

**Comment by Passer1072** [comment]
> MOUSEEVENTF_MOVE = 0x0001 ctypes.windll.user32.mouse_event(MOUSEEVENTF_MOVE, x, y, 0, 0)

`ctypes `方式与 `win32api `方式原理相似，均为通过调用`Windows API`来实现移动，区别在于语法上有少许不一样，理论上功能与原理没有任何区别，可能没有添加的必要？

**Comment by loy0516** [comment]
确实
