### ISSUE TITLE
闪退问题如何解决

### ISSUE THREAD

**Issue by yecao1016** [Passer1072/RookieAI_yolov8#65]
**Describe the bug**

描述问题的清晰而简明的说明

**To Reproduce**

Steps to reproduce the behavior.

重现行为的步骤

**Expected behavior**

期望发生的行为的清晰而简明的描述

**Screenshots**

如果适用，请添加截图以帮助解释您的问题

**Equipment information:**

 - Platform(系统架构): [e.g. Windows 10/11]
 - RookieAI version(RookieAI版本): [e.g. v2.3.2]
 - Python version(Python版本): [e.g. 3.10.1]

**Additional context**

在这里添加关于问题的其他相关信息

**Comment by molanp** [comment]
是否安装相关依赖

**Comment by yecao1016** [comment]
> 是否安装相关依赖
是requirements.txt吗?我已经全部安装了

**Comment by molanp** [comment]
能否捕获到闪退瞬间控制台日志，
请提供你的启动步骤
