### ISSUE TITLE
为什么开启后没有效果

### ISSUE THREAD

**Issue by yecao1016** [Passer1072/RookieAI_yolov8#67]
![083b05902820705ed217777f7a438f6d](https://github.com/user-attachments/assets/dfac67d6-2405-483d-98d3-ad5d1740dfee)
![736132b01fa07ae00244bc7232515a67](https://github.com/user-attachments/assets/c664005e-2183-4fc5-9953-7af632fdf11f)

**Comment by molanp** [comment]
脚本打包异常

请尝试不要打包，使用控制台直接运行脚本

**Comment by molanp** [comment]
已更新使用教程
