### ISSUE TITLE
识别没啥问题 打包也没啥问题了 就是控制鼠标上有点问题

### ISSUE THREAD

**Issue by mransin** [Passer1072/RookieAI_yolov8#69]
鼠标会乱跳？ 锁不住人 是识别帧率太低了吗 我看识别帧率只有30fps左右

**Comment by Passer1072** [comment]
是的太低了，尝试使用atlas系统，或降低截图范围

ansin ***@***.***>于2024年11月11日 周一下午7:46写道：
