### ISSUE TITLE
奇怪的报错，需要处理吗

### ISSUE THREAD

**Issue by jimstf7** [Passer1072/RookieAI_yolov8#71]
[ERROR]光流计算错误: OpenCV(4.9.0) D:\a\opencv-python\opencv-python\opencv\modules\video\src\lkpyramid.cpp:1260: error: (-215:Assertion failed) (npoints = prevPtsMat.checkVector(2, CV_32F, true)) >= 0 in function 'cv::`anonymous-namespace'::SparsePyrLKOpticalFlowImpl::calc'

CUDA python torch都检查过了 版本分别是 python (3.11.6) pip (24.3.1) torch (2.2.0) CUDA(12.1) 大佬求教

![屏幕截图 2024-11-12 215505](https://github.com/user-attachments/assets/eeaaeb80-7564-4313-899b-a2eccbf1b3d9)

**Comment by molanp** [comment]
重新安装依赖

```shell
pip uninstall torch torchvision torchaudio

pip install torch torchvision torchaudio -f https://mirror.sjtu.edu.cn/pytorch-wheels/torch_stable.html --no-index
```

**Comment by molanp** [comment]
torch版本不是必须2.2.0，此命令会安装合适的版本，

理论上按照readme里的开发者教程会自动安装合适的版本

**Comment by jimstf7** [comment]
ok谢谢

**Comment by jimstf7** [comment]
还有一个问题, 现在fortnite用win32鼠标移动库会被ban吗，会检测出来吗

**Comment by molanp** [comment]
> 还有一个问题, 现在fortnite用win32鼠标移动库会被ban吗，会检测出来吗
> 

不清楚，可以换用mouse或罗技驱动

**Comment by Passer1072** [comment]
> 还有一个问题, 现在fortnite用win32鼠标移动库会被ban吗，会检测出来吗

只要不在tx的游戏上用基本没有问题，除非参数异常导致鼠标乱动被检测到鼠标移动异常会被ban，小蓝熊是没有问题的。参数也别开高了。
