### ISSUE TITLE
是否可以创建像telegra类似的群 来讨论问题

### ISSUE THREAD

**Issue by joker0317** [Passer1072/RookieAI_yolov8#75]
**Is your feature request related to a problem? Please describe.**

**您的功能请求是否与某个问题相关？请描述清楚**

Type here.

**Describe the features you need to add.**

**描述您希望增加的功能**

Type here.

**Describe alternatives you've considered**

**描述您考虑过的任何备选解决方案或功能**

Type here.

**Additional context**

在此处添加关于功能请求的任何其他上下文或截图

**Comment by molanp** [comment]
已计划

**Comment by joker0317** [comment]
> 已计划
如果创建 了记得叫我吖

**Comment by Passer1072** [comment]
> > 已计划
> > 如果创建 了记得叫我吖

欢迎加入discord
https://discord.gg/vtgbfy2afb
