### ISSUE TITLE
一直报错UI界面里的滑块条对象未找到，请求指点解决

### ISSUE THREAD

**Issue by worinimaa** [Passer1072/RookieAI_yolov8#77]
![bc](https://github.com/user-attachments/assets/220b951a-246b-4711-a6ae-40ae5032bb26)
一直报错这个信息，麻烦问下是什么原因，研究了代码，代码里
![bc](https://github.com/user-attachments/assets/30d02a9c-0b8d-4d00-9784-622cccbc9608)
没发现错误。。

**Comment by molanp** [comment]
目前dev分支尚未完工，需要等待一定时间，请下载main分支

**Comment by worinimaa** [comment]
我下载的就是main分支，2.5.7版本之前都能启动使用，就这个3.0版本报错一直解决不了

**Comment by molanp** [comment]
3.0尚未完工，使用release版本

**Comment by Passer1072** [comment]
> 我下载的就是main分支，2.5.7版本之前都能启动使用，就这个3.0版本报错一直解决不了

V3功能未完善，并且性能提升没有非常明显，如果V2可以继续用就先接着用没有问题。

**Comment by worinimaa** [comment]
好的，谢谢，还有一个打包后的问题：
打包后pt模型能使用，onnx和eng模型一直提示onnx onnxruntime和Tensort模块没有找到，能告诉下是什么原因吗？我打包时加了这三个模块也不行

**Comment by molanp** [comment]
> 好的，谢谢，还有一个打包后的问题： 打包后pt模型能使用，onnx和eng模型一直提示onnx onnxruntime和Tensort模块没有找到，能告诉下是什么原因吗？我打包时加了这三个模块也不行

不要打包，参考开发者教程运行

**Comment by molanp** [comment]
> 好的，谢谢，还有一个打包后的问题：
> 打包后pt模型能使用，onnx和eng模型一直提示onnx onnxruntime和Tensort模块没有找到，能告诉下是什么原因吗？我打包时加了这三个模块也不行

这三个模块打包不仅需要 `hiddenimport`参数，还需要通过`add-data`附加模块路径才能正常包含全部内容
