### ISSUE TITLE
 inferênce model 

### ISSUE THREAD

**Issue by CougarP** [Passer1072/RookieAI_yolov8#8]
You have a forecast to add Onnx and models. TRT

**Comment by Passer1072** [comment]
Sorry, due to personal time reasons, plans to support the onnx model are currently suspended. But I don't plan to give up on this plan, I will start again when I have enough time. The Pytorch model will theoretically have better performance, you can try it!

**Comment by Passer1072** [comment]
TRT models are now supported.
