### ISSUE TITLE
在终端运行这个程序后，要打开哪些游戏才能实现效果

### ISSUE THREAD

**Issue by tianwu555** [Passer1072/RookieAI_yolov8#81]
运行软件的时候显示系统识别不到GUDA设备
![屏幕截图 2024-12-17 093608](https://github.com/user-attachments/assets/6964fa92-55e7-4e5c-8522-461b3345feeb)

在终端运行这个程序后，要打开哪些游戏才能实现效果，打开游戏后还需要进行哪些操作，求求作者告知，谢谢作者

**Comment by Passer1072** [comment]
不支持amd显卡以及核显

tianwu555 ***@***.***>于2024年12月17日 周二上午9:44写道：
